export const packetNames = {
  test: {
    GlobalFailCode: 'test.GlobalFailCode',
    Position: 'test.Position',
    BaseData: 'test.BaseData',
    TowerData: 'test.TowerData',
    MonsterData: 'test.MonsterData',
    InitialGameState: 'test.InitialGameState',
    GameState: 'test.GameState',
    C2SRegisterRequest: 'test.C2SRegisterRequest',
    S2CRegisterResponse: 'test.S2CRegisterResponse',
    C2SLoginRequest: 'test.C2SLoginRequest',
    S2CLoginResponse: 'test.S2CLoginResponse',
    C2SMatchRequest: 'test.C2SMatchRequest',
    S2CMatchStartNotification: 'test.S2CMatchStartNotification',
    S2CStateSyncNotification: 'test.S2CStateSyncNotification',
    C2STowerPurchaseRequest: 'test.C2STowerPurchaseRequest',
    S2CTowerPurchaseResponse: 'test.S2CTowerPurchaseResponse',
    S2CAddEnemyTowerNotification: 'test.S2CAddEnemyTowerNotification',
    C2SSpawnMonsterRequest: 'test.C2SSpawnMonsterRequest',
    S2CSpawnMonsterResponse: 'test.S2CSpawnMonsterResponse',
    S2CSpawnEnemyMonsterNotification: 'test.S2CSpawnEnemyMonsterNotification',
    C2STowerAttackRequest: 'test.C2STowerAttackRequest',
    S2CEnemyTowerAttackNotification: 'test.S2CEnemyTowerAttackNotification',
    C2SMonsterAttackBaseRequest: 'test.C2SMonsterAttackBaseRequest',
    S2CUpdateBaseHPNotification: 'test.S2CUpdateBaseHPNotification',
    S2CGameOverNotification: 'test.S2CGameOverNotification',
    C2SGameEndRequest: 'test.C2SGameEndRequest',
    C2SMonsterDeathNotification: 'test.C2SMonsterDeathNotification',
    S2CEnemyMonsterDeathNotification: 'test.S2CEnemyMonsterDeathNotification',
    GamePacket: 'test.GamePacket',
  },
};
