export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  LOGIN_REQUEST: 1,
  LOGIN_RESPONSE: 2,
  MATCH_START_NOTIFICATION: 1001,
  STATE_SYNC_NOTIFICATION: 1002,
  ADD_ENEMY_TOWER_NOTIFICATION: 1003,
  SPAWN_ENEMY_MONSTER_NOTIFICATION: 1004,
  UPDATE_BASE_HP_NOTIFICATION: 1005,
  GAME_OVER_NOTIFICATION: 1006,
  MONSTER_DEATH_NOTIFICATION: 1007,
  ENEMY_MONSTER_DEATH_NOTIFICATION: 1008,
  MATCH_REQUEST: 900,
};
